### PR TITLE
Added Classes and Functions + Code Cleanup

### PR DESCRIPTION
**Pull request by Irtiza90**
Added 2 Classes HttpStatus and BakaMessages

HttpStatus Class is For Storing The Different Http Statues (Import More Status Codes from http.client and add them to class with .real)
BakaMessages Class Is For Storing the hi, and bye Message List, To Use them do BakaMessages.bye_message()

Reduced Alot Of the Code in Class Baka(The commented Code is the Reduced One)

Added 2 Functions

remove_qparam, Basically does what you were doing with this self.path.split("?")[0], There were so many of these that i made a function for it
send_response_ Function Removes a Ton Of Repetitive Code, Read the function Doncstrings For More Info on Parameters

Took like 4 Hours to Do This, Also You might need to do a little bit of Testing

### CODE REVIEW

**Comment by Irtiza90** [comment]
Hope You Appreciate It

**Comment by aydaultani** [comment]
That's amazing! I'll need to do some tests as you said to actually make sure it doesn't break stuff! Give me a few days :)
Thanks a lot,
Cheers Arnav

**Comment by Irtiza90** [comment]
It's been 11 days. Did the code break something?

**Comment by aydaultani** [comment]
> It's been 11 days. Did the code break something?

I haven't gotten the time to test it due to exams and other projects, could you run it on your local machine and test all the features which you changed and see if it breaks for you.

**Comment by Irtiza90** [comment]
I have exactly the same excuse lol,
I'll test it when i can

**Comment by aydaultani** [comment]
Merging this, hope it doesn't break prod!

**Pull request merged**
